name: Build and deploy to web hosting (cPanel)

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build_and_deploy:
    name: Build and Deploy the API server.
    runs-on: ubuntu-latest
    env:
      HOSTING_APP_ROOT: ${{ secrets.HOSTING_APP_ROOT }}
    steps:
      - name: Check out source
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: 22
          cache: "npm"

      - run: npm ci

      - run: npm run build

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$HOSTING_SSH_KEY" > ~/.ssh/hosting.key
          chmod 600 ~/.ssh/hosting.key
          cat >>~/.ssh/config <<END
          Host hosting
            HostName $HOSTING_SSH_HOST
            Port $HOSTING_SSH_HOST_PORT
            User $HOSTING_SSH_USER
            IdentityFile ~/.ssh/hosting.key
            StrictHostKeyChecking no
            BatchMode yes
            PubkeyAuthentication yes
          END
        env:
          HOSTING_SSH_HOST: ${{ secrets.HOSTING_SSH_HOST }}
          HOSTING_SSH_HOST_PORT: ${{ secrets.HOSTING_SSH_HOST_PORT }}
          HOSTING_SSH_USER: ${{ secrets.HOSTING_SSH_USER }}
          HOSTING_SSH_KEY: ${{ secrets.HOSTING_SSH_KEY }}

      - name: Stop the node app
        run: ssh hosting "/usr/sbin/cloudlinux-selector stop --json --interpreter nodejs --app-root $HOSTING_APP_ROOT"

      - name: Remove old distribution
        run: ssh hosting "rm -rf $HOSTING_APP_ROOT/dist"

      - name: Copy package file
        run: scp package.json "hosting:$HOSTING_APP_ROOT"

      - name: Copy package lock
        run: scp package-lock.json "hosting:$HOSTING_APP_ROOT"

      - name: Copy distribution
        run: scp -r dist/ "hosting:$HOSTING_APP_ROOT"

      - name: Install modules
        run: ssh hosting "/usr/sbin/cloudlinux-selector install-modules --json --interpreter nodejs --app-root $HOSTING_APP_ROOT"

      - name: Start the node app
        run: ssh hosting "/usr/sbin/cloudlinux-selector start --json --interpreter nodejs --app-root $HOSTING_APP_ROOT"
